# Generated by Django 4.2.6 on 2023-10-30 18:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Hoja_Vida',
            field=ckeditor.fields.RichTextField(default='texto de hoja de vida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Computación')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
