# Generated by Django 4.2.6 on 2023-11-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cprueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
